// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/nanit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_PUT_STREAMING       RequestType = 2
	RequestType_GET_STREAMING       RequestType = 3
	RequestType_GET_SETTINGS        RequestType = 4
	RequestType_PUT_SETTINGS        RequestType = 5
	RequestType_GET_CONTROL         RequestType = 6
	RequestType_PUT_CONTROL         RequestType = 7
	RequestType_GET_STATUS          RequestType = 8
	RequestType_PUT_STATUS          RequestType = 9
	RequestType_PUT_SENSOR_DATA     RequestType = 11
	RequestType_GET_SENSOR_DATA     RequestType = 12
	RequestType_GET_UCTOKENS        RequestType = 13
	RequestType_PUT_UCTOKENS        RequestType = 14
	RequestType_PUT_SETUP_NETWORK   RequestType = 15
	RequestType_PUT_SETUP_SERVER    RequestType = 16
	RequestType_GET_FIRMWARE        RequestType = 17
	RequestType_PUT_FIRMWARE        RequestType = 18
	RequestType_GET_PLAYBACK        RequestType = 19
	RequestType_PUT_PLAYBACK        RequestType = 20
	RequestType_GET_SOUNDTRACKS     RequestType = 21
	RequestType_GET_STATUS_NETWORK  RequestType = 22
	RequestType_GET_LIST_NETWORKS   RequestType = 23
	RequestType_GET_LOGS            RequestType = 24
	RequestType_GET_BANDWIDTH       RequestType = 25
	RequestType_GET_AUDIO_STREAMING RequestType = 26
	RequestType_PUT_AUDIO_STREAMING RequestType = 27
	RequestType_GET_WIFI_SETUP      RequestType = 28
	RequestType_PUT_WIFI_SETUP      RequestType = 29
	RequestType_PUT_STING_START     RequestType = 30
	RequestType_PUT_STING_STOP      RequestType = 31
	RequestType_PUT_STING_STATUS    RequestType = 32
	RequestType_PUT_STING_ALERT     RequestType = 34
	RequestType_PUT_KEEP_ALIVE      RequestType = 35
	RequestType_GET_STING_STATUS    RequestType = 36
	RequestType_PUT_STING_TEST      RequestType = 37
	RequestType_PUT_RTSP_STREAMING  RequestType = 38
	RequestType_GET_UOM_URI         RequestType = 39
	RequestType_GET_UOM             RequestType = 40
	RequestType_PUT_UOM             RequestType = 41
	RequestType_GET_AUTH_KEY        RequestType = 42
	RequestType_PUT_AUTH_KEY        RequestType = 43
	RequestType_PUT_HEALTH          RequestType = 44
	RequestType_PUT_TCP_REQUEST     RequestType = 45
	RequestType_GET_STING_START     RequestType = 46
	RequestType_GET_LOGS_URI        RequestType = 47
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		2:  "PUT_STREAMING",
		3:  "GET_STREAMING",
		4:  "GET_SETTINGS",
		5:  "PUT_SETTINGS",
		6:  "GET_CONTROL",
		7:  "PUT_CONTROL",
		8:  "GET_STATUS",
		9:  "PUT_STATUS",
		11: "PUT_SENSOR_DATA",
		12: "GET_SENSOR_DATA",
		13: "GET_UCTOKENS",
		14: "PUT_UCTOKENS",
		15: "PUT_SETUP_NETWORK",
		16: "PUT_SETUP_SERVER",
		17: "GET_FIRMWARE",
		18: "PUT_FIRMWARE",
		19: "GET_PLAYBACK",
		20: "PUT_PLAYBACK",
		21: "GET_SOUNDTRACKS",
		22: "GET_STATUS_NETWORK",
		23: "GET_LIST_NETWORKS",
		24: "GET_LOGS",
		25: "GET_BANDWIDTH",
		26: "GET_AUDIO_STREAMING",
		27: "PUT_AUDIO_STREAMING",
		28: "GET_WIFI_SETUP",
		29: "PUT_WIFI_SETUP",
		30: "PUT_STING_START",
		31: "PUT_STING_STOP",
		32: "PUT_STING_STATUS",
		34: "PUT_STING_ALERT",
		35: "PUT_KEEP_ALIVE",
		36: "GET_STING_STATUS",
		37: "PUT_STING_TEST",
		38: "PUT_RTSP_STREAMING",
		39: "GET_UOM_URI",
		40: "GET_UOM",
		41: "PUT_UOM",
		42: "GET_AUTH_KEY",
		43: "PUT_AUTH_KEY",
		44: "PUT_HEALTH",
		45: "PUT_TCP_REQUEST",
		46: "GET_STING_START",
		47: "GET_LOGS_URI",
	}
	RequestType_value = map[string]int32{
		"PUT_STREAMING":       2,
		"GET_STREAMING":       3,
		"GET_SETTINGS":        4,
		"PUT_SETTINGS":        5,
		"GET_CONTROL":         6,
		"PUT_CONTROL":         7,
		"GET_STATUS":          8,
		"PUT_STATUS":          9,
		"PUT_SENSOR_DATA":     11,
		"GET_SENSOR_DATA":     12,
		"GET_UCTOKENS":        13,
		"PUT_UCTOKENS":        14,
		"PUT_SETUP_NETWORK":   15,
		"PUT_SETUP_SERVER":    16,
		"GET_FIRMWARE":        17,
		"PUT_FIRMWARE":        18,
		"GET_PLAYBACK":        19,
		"PUT_PLAYBACK":        20,
		"GET_SOUNDTRACKS":     21,
		"GET_STATUS_NETWORK":  22,
		"GET_LIST_NETWORKS":   23,
		"GET_LOGS":            24,
		"GET_BANDWIDTH":       25,
		"GET_AUDIO_STREAMING": 26,
		"PUT_AUDIO_STREAMING": 27,
		"GET_WIFI_SETUP":      28,
		"PUT_WIFI_SETUP":      29,
		"PUT_STING_START":     30,
		"PUT_STING_STOP":      31,
		"PUT_STING_STATUS":    32,
		"PUT_STING_ALERT":     34,
		"PUT_KEEP_ALIVE":      35,
		"GET_STING_STATUS":    36,
		"PUT_STING_TEST":      37,
		"PUT_RTSP_STREAMING":  38,
		"GET_UOM_URI":         39,
		"GET_UOM":             40,
		"PUT_UOM":             41,
		"GET_AUTH_KEY":        42,
		"PUT_AUTH_KEY":        43,
		"PUT_HEALTH":          44,
		"PUT_TCP_REQUEST":     45,
		"GET_STING_START":     46,
		"GET_LOGS_URI":        47,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestType(num)
	return nil
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{0}
}

type SensorType int32

const (
	SensorType_SOUND       SensorType = 0
	SensorType_MOTION      SensorType = 1
	SensorType_TEMPERATURE SensorType = 2
	SensorType_HUMIDITY    SensorType = 3
	SensorType_LIGHT       SensorType = 4
	SensorType_NIGHT       SensorType = 5
)

// Enum value maps for SensorType.
var (
	SensorType_name = map[int32]string{
		0: "SOUND",
		1: "MOTION",
		2: "TEMPERATURE",
		3: "HUMIDITY",
		4: "LIGHT",
		5: "NIGHT",
	}
	SensorType_value = map[string]int32{
		"SOUND":       0,
		"MOTION":      1,
		"TEMPERATURE": 2,
		"HUMIDITY":    3,
		"LIGHT":       4,
		"NIGHT":       5,
	}
)

func (x SensorType) Enum() *SensorType {
	p := new(SensorType)
	*p = x
	return p
}

func (x SensorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[1].Descriptor()
}

func (SensorType) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[1]
}

func (x SensorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SensorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SensorType(num)
	return nil
}

// Deprecated: Use SensorType.Descriptor instead.
func (SensorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{1}
}

type StreamIdentifier int32

const (
	StreamIdentifier_DVR       StreamIdentifier = 0
	StreamIdentifier_ANALYTICS StreamIdentifier = 1
	StreamIdentifier_MOBILE    StreamIdentifier = 2
)

// Enum value maps for StreamIdentifier.
var (
	StreamIdentifier_name = map[int32]string{
		0: "DVR",
		1: "ANALYTICS",
		2: "MOBILE",
	}
	StreamIdentifier_value = map[string]int32{
		"DVR":       0,
		"ANALYTICS": 1,
		"MOBILE":    2,
	}
)

func (x StreamIdentifier) Enum() *StreamIdentifier {
	p := new(StreamIdentifier)
	*p = x
	return p
}

func (x StreamIdentifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamIdentifier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[2].Descriptor()
}

func (StreamIdentifier) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[2]
}

func (x StreamIdentifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamIdentifier) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamIdentifier(num)
	return nil
}

// Deprecated: Use StreamIdentifier.Descriptor instead.
func (StreamIdentifier) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{2}
}

type MountingMode int32

const (
	MountingMode_STAND  MountingMode = 0
	MountingMode_TRAVEL MountingMode = 1
	MountingMode_SWITCH MountingMode = 2
)

// Enum value maps for MountingMode.
var (
	MountingMode_name = map[int32]string{
		0: "STAND",
		1: "TRAVEL",
		2: "SWITCH",
	}
	MountingMode_value = map[string]int32{
		"STAND":  0,
		"TRAVEL": 1,
		"SWITCH": 2,
	}
)

func (x MountingMode) Enum() *MountingMode {
	p := new(MountingMode)
	*p = x
	return p
}

func (x MountingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[3].Descriptor()
}

func (MountingMode) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[3]
}

func (x MountingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MountingMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MountingMode(num)
	return nil
}

// Deprecated: Use MountingMode.Descriptor instead.
func (MountingMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{3}
}

type Control_NightLight int32

const (
	Control_LIGHT_OFF Control_NightLight = 0
	Control_LIGHT_ON  Control_NightLight = 1
)

// Enum value maps for Control_NightLight.
var (
	Control_NightLight_name = map[int32]string{
		0: "LIGHT_OFF",
		1: "LIGHT_ON",
	}
	Control_NightLight_value = map[string]int32{
		"LIGHT_OFF": 0,
		"LIGHT_ON":  1,
	}
)

func (x Control_NightLight) Enum() *Control_NightLight {
	p := new(Control_NightLight)
	*p = x
	return p
}

func (x Control_NightLight) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Control_NightLight) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[4].Descriptor()
}

func (Control_NightLight) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[4]
}

func (x Control_NightLight) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Control_NightLight) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Control_NightLight(num)
	return nil
}

// Deprecated: Use Control_NightLight.Descriptor instead.
func (Control_NightLight) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{3, 0}
}

type Settings_AntiFlicker int32

const (
	Settings_FR50HZ Settings_AntiFlicker = 0
	Settings_FR60HZ Settings_AntiFlicker = 1
)

// Enum value maps for Settings_AntiFlicker.
var (
	Settings_AntiFlicker_name = map[int32]string{
		0: "FR50HZ",
		1: "FR60HZ",
	}
	Settings_AntiFlicker_value = map[string]int32{
		"FR50HZ": 0,
		"FR60HZ": 1,
	}
)

func (x Settings_AntiFlicker) Enum() *Settings_AntiFlicker {
	p := new(Settings_AntiFlicker)
	*p = x
	return p
}

func (x Settings_AntiFlicker) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Settings_AntiFlicker) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[5].Descriptor()
}

func (Settings_AntiFlicker) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[5]
}

func (x Settings_AntiFlicker) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Settings_AntiFlicker) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Settings_AntiFlicker(num)
	return nil
}

// Deprecated: Use Settings_AntiFlicker.Descriptor instead.
func (Settings_AntiFlicker) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{4, 0}
}

type Settings_WifiBand int32

const (
	Settings_ANY      Settings_WifiBand = 0
	Settings_FR2_4GHZ Settings_WifiBand = 1
	Settings_FR5_0GHZ Settings_WifiBand = 2
)

// Enum value maps for Settings_WifiBand.
var (
	Settings_WifiBand_name = map[int32]string{
		0: "ANY",
		1: "FR2_4GHZ",
		2: "FR5_0GHZ",
	}
	Settings_WifiBand_value = map[string]int32{
		"ANY":      0,
		"FR2_4GHZ": 1,
		"FR5_0GHZ": 2,
	}
)

func (x Settings_WifiBand) Enum() *Settings_WifiBand {
	p := new(Settings_WifiBand)
	*p = x
	return p
}

func (x Settings_WifiBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Settings_WifiBand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[6].Descriptor()
}

func (Settings_WifiBand) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[6]
}

func (x Settings_WifiBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Settings_WifiBand) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Settings_WifiBand(num)
	return nil
}

// Deprecated: Use Settings_WifiBand.Descriptor instead.
func (Settings_WifiBand) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{4, 1}
}

type Status_ConnectionToServer int32

const (
	Status_DISCONNECTED Status_ConnectionToServer = 0
	Status_CONNECTED    Status_ConnectionToServer = 1
)

// Enum value maps for Status_ConnectionToServer.
var (
	Status_ConnectionToServer_name = map[int32]string{
		0: "DISCONNECTED",
		1: "CONNECTED",
	}
	Status_ConnectionToServer_value = map[string]int32{
		"DISCONNECTED": 0,
		"CONNECTED":    1,
	}
)

func (x Status_ConnectionToServer) Enum() *Status_ConnectionToServer {
	p := new(Status_ConnectionToServer)
	*p = x
	return p
}

func (x Status_ConnectionToServer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_ConnectionToServer) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[7].Descriptor()
}

func (Status_ConnectionToServer) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[7]
}

func (x Status_ConnectionToServer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Status_ConnectionToServer) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Status_ConnectionToServer(num)
	return nil
}

// Deprecated: Use Status_ConnectionToServer.Descriptor instead.
func (Status_ConnectionToServer) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{5, 0}
}

type Playback_Status int32

const (
	Playback_STARTED Playback_Status = 0
	Playback_STOPPED Playback_Status = 1
)

// Enum value maps for Playback_Status.
var (
	Playback_Status_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
	}
	Playback_Status_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
	}
)

func (x Playback_Status) Enum() *Playback_Status {
	p := new(Playback_Status)
	*p = x
	return p
}

func (x Playback_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Playback_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[8].Descriptor()
}

func (Playback_Status) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[8]
}

func (x Playback_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Playback_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Playback_Status(num)
	return nil
}

// Deprecated: Use Playback_Status.Descriptor instead.
func (Playback_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{6, 0}
}

type Stream_Type int32

const (
	Stream_LOCAL  Stream_Type = 0
	Stream_REMOTE Stream_Type = 1
	Stream_RTSP   Stream_Type = 2
	Stream_P2P    Stream_Type = 3
)

// Enum value maps for Stream_Type.
var (
	Stream_Type_name = map[int32]string{
		0: "LOCAL",
		1: "REMOTE",
		2: "RTSP",
		3: "P2P",
	}
	Stream_Type_value = map[string]int32{
		"LOCAL":  0,
		"REMOTE": 1,
		"RTSP":   2,
		"P2P":    3,
	}
)

func (x Stream_Type) Enum() *Stream_Type {
	p := new(Stream_Type)
	*p = x
	return p
}

func (x Stream_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[9].Descriptor()
}

func (Stream_Type) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[9]
}

func (x Stream_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Stream_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Stream_Type(num)
	return nil
}

// Deprecated: Use Stream_Type.Descriptor instead.
func (Stream_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{7, 0}
}

type Streaming_Status int32

const (
	Streaming_STARTED Streaming_Status = 0
	Streaming_STOPPED Streaming_Status = 1
	Streaming_PAUSED  Streaming_Status = 2
)

// Enum value maps for Streaming_Status.
var (
	Streaming_Status_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
		2: "PAUSED",
	}
	Streaming_Status_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
		"PAUSED":  2,
	}
)

func (x Streaming_Status) Enum() *Streaming_Status {
	p := new(Streaming_Status)
	*p = x
	return p
}

func (x Streaming_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Streaming_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[10].Descriptor()
}

func (Streaming_Status) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[10]
}

func (x Streaming_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Streaming_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Streaming_Status(num)
	return nil
}

// Deprecated: Use Streaming_Status.Descriptor instead.
func (Streaming_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{8, 0}
}

type Message_Type int32

const (
	Message_KEEPALIVE Message_Type = 0
	Message_REQUEST   Message_Type = 1
	Message_RESPONSE  Message_Type = 2
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "KEEPALIVE",
		1: "REQUEST",
		2: "RESPONSE",
	}
	Message_Type_value = map[string]int32{
		"KEEPALIVE": 0,
		"REQUEST":   1,
		"RESPONSE":  2,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nanit_proto_enumTypes[11].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_proto_nanit_proto_enumTypes[11]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Message_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Message_Type(num)
	return nil
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{13, 0}
}

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorType    *SensorType            `protobuf:"varint,1,req,name=sensor_type,json=sensorType,enum=nanit.SensorType" json:"sensor_type,omitempty"`
	Value         *int32                 `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	IsAlert       *bool                  `protobuf:"varint,4,opt,name=is_alert,json=isAlert" json:"is_alert,omitempty"`
	Timestamp     *int32                 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	ValueMilli    *int32                 `protobuf:"varint,6,opt,name=value_milli,json=valueMilli" json:"value_milli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_proto_nanit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetSensorType() SensorType {
	if x != nil && x.SensorType != nil {
		return *x.SensorType
	}
	return SensorType_SOUND
}

func (x *SensorData) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SensorData) GetIsAlert() bool {
	if x != nil && x.IsAlert != nil {
		return *x.IsAlert
	}
	return false
}

func (x *SensorData) GetTimestamp() int32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *SensorData) GetValueMilli() int32 {
	if x != nil && x.ValueMilli != nil {
		return *x.ValueMilli
	}
	return 0
}

type GetSensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           *bool                  `protobuf:"varint,1,opt,name=all" json:"all,omitempty"`
	Temperature   *bool                  `protobuf:"varint,4,opt,name=temperature" json:"temperature,omitempty"`
	Humidity      *bool                  `protobuf:"varint,5,opt,name=humidity" json:"humidity,omitempty"`
	Light         *bool                  `protobuf:"varint,6,opt,name=light" json:"light,omitempty"`
	Night         *bool                  `protobuf:"varint,7,opt,name=night" json:"night,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSensorData) Reset() {
	*x = GetSensorData{}
	mi := &file_proto_nanit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSensorData) ProtoMessage() {}

func (x *GetSensorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSensorData.ProtoReflect.Descriptor instead.
func (*GetSensorData) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{1}
}

func (x *GetSensorData) GetAll() bool {
	if x != nil && x.All != nil {
		return *x.All
	}
	return false
}

func (x *GetSensorData) GetTemperature() bool {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return false
}

func (x *GetSensorData) GetHumidity() bool {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return false
}

func (x *GetSensorData) GetLight() bool {
	if x != nil && x.Light != nil {
		return *x.Light
	}
	return false
}

func (x *GetSensorData) GetNight() bool {
	if x != nil && x.Night != nil {
		return *x.Night
	}
	return false
}

type GetControl struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ptz                  *bool                  `protobuf:"varint,1,opt,name=ptz" json:"ptz,omitempty"`
	NightLight           *bool                  `protobuf:"varint,2,opt,name=night_light,json=nightLight" json:"night_light,omitempty"`
	NightLightTimeout    *bool                  `protobuf:"varint,3,opt,name=night_light_timeout,json=nightLightTimeout" json:"night_light_timeout,omitempty"`
	SensorDataTransferEn *bool                  `protobuf:"varint,4,opt,name=sensor_data_transfer_en,json=sensorDataTransferEn" json:"sensor_data_transfer_en,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetControl) Reset() {
	*x = GetControl{}
	mi := &file_proto_nanit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControl) ProtoMessage() {}

func (x *GetControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControl.ProtoReflect.Descriptor instead.
func (*GetControl) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{2}
}

func (x *GetControl) GetPtz() bool {
	if x != nil && x.Ptz != nil {
		return *x.Ptz
	}
	return false
}

func (x *GetControl) GetNightLight() bool {
	if x != nil && x.NightLight != nil {
		return *x.NightLight
	}
	return false
}

func (x *GetControl) GetNightLightTimeout() bool {
	if x != nil && x.NightLightTimeout != nil {
		return *x.NightLightTimeout
	}
	return false
}

func (x *GetControl) GetSensorDataTransferEn() bool {
	if x != nil && x.SensorDataTransferEn != nil {
		return *x.SensorDataTransferEn
	}
	return false
}

type Control struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	NightLight           *Control_NightLight         `protobuf:"varint,3,opt,name=night_light,json=nightLight,enum=nanit.Control_NightLight" json:"night_light,omitempty"`
	SensorDataTransfer   *Control_SensorDataTransfer `protobuf:"bytes,4,opt,name=sensor_data_transfer,json=sensorDataTransfer" json:"sensor_data_transfer,omitempty"`
	ForceConnectToServer *bool                       `protobuf:"varint,5,opt,name=force_connect_to_server,json=forceConnectToServer" json:"force_connect_to_server,omitempty"`
	NightLightTimeout    *int32                      `protobuf:"varint,6,opt,name=night_light_timeout,json=nightLightTimeout" json:"night_light_timeout,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_proto_nanit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{3}
}

func (x *Control) GetNightLight() Control_NightLight {
	if x != nil && x.NightLight != nil {
		return *x.NightLight
	}
	return Control_LIGHT_OFF
}

func (x *Control) GetSensorDataTransfer() *Control_SensorDataTransfer {
	if x != nil {
		return x.SensorDataTransfer
	}
	return nil
}

func (x *Control) GetForceConnectToServer() bool {
	if x != nil && x.ForceConnectToServer != nil {
		return *x.ForceConnectToServer
	}
	return false
}

func (x *Control) GetNightLightTimeout() int32 {
	if x != nil && x.NightLightTimeout != nil {
		return *x.NightLightTimeout
	}
	return 0
}

type Settings struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	NightVision   *bool                      `protobuf:"varint,2,opt,name=night_vision,json=nightVision" json:"night_vision,omitempty"`
	Sensors       []*Settings_SensorSettings `protobuf:"bytes,7,rep,name=sensors" json:"sensors,omitempty"`
	Streams       []*Settings_StreamSettings `protobuf:"bytes,8,rep,name=streams" json:"streams,omitempty"`
	Volume        *int32                     `protobuf:"varint,9,opt,name=volume" json:"volume,omitempty"`
	AntiFlicker   *Settings_AntiFlicker      `protobuf:"varint,10,opt,name=anti_flicker,json=antiFlicker,enum=nanit.Settings_AntiFlicker" json:"anti_flicker,omitempty"`
	SleepMode     *bool                      `protobuf:"varint,11,opt,name=sleep_mode,json=sleepMode" json:"sleep_mode,omitempty"`
	StatusLightOn *bool                      `protobuf:"varint,12,opt,name=status_light_on,json=statusLightOn" json:"status_light_on,omitempty"`
	MountingMode  *int32                     `protobuf:"varint,15,opt,name=mounting_mode,json=mountingMode" json:"mounting_mode,omitempty"`
	WifiBand      *Settings_WifiBand         `protobuf:"varint,18,opt,name=wifi_band,json=wifiBand,enum=nanit.Settings_WifiBand" json:"wifi_band,omitempty"`
	MicMuteOn     *bool                      `protobuf:"varint,20,opt,name=mic_mute_on,json=micMuteOn" json:"mic_mute_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_proto_nanit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{4}
}

func (x *Settings) GetNightVision() bool {
	if x != nil && x.NightVision != nil {
		return *x.NightVision
	}
	return false
}

func (x *Settings) GetSensors() []*Settings_SensorSettings {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *Settings) GetStreams() []*Settings_StreamSettings {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *Settings) GetVolume() int32 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *Settings) GetAntiFlicker() Settings_AntiFlicker {
	if x != nil && x.AntiFlicker != nil {
		return *x.AntiFlicker
	}
	return Settings_FR50HZ
}

func (x *Settings) GetSleepMode() bool {
	if x != nil && x.SleepMode != nil {
		return *x.SleepMode
	}
	return false
}

func (x *Settings) GetStatusLightOn() bool {
	if x != nil && x.StatusLightOn != nil {
		return *x.StatusLightOn
	}
	return false
}

func (x *Settings) GetMountingMode() int32 {
	if x != nil && x.MountingMode != nil {
		return *x.MountingMode
	}
	return 0
}

func (x *Settings) GetWifiBand() Settings_WifiBand {
	if x != nil && x.WifiBand != nil {
		return *x.WifiBand
	}
	return Settings_ANY
}

func (x *Settings) GetMicMuteOn() bool {
	if x != nil && x.MicMuteOn != nil {
		return *x.MicMuteOn
	}
	return false
}

type Status struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	UpgradeDownloaded  *bool                      `protobuf:"varint,1,opt,name=upgrade_downloaded,json=upgradeDownloaded" json:"upgrade_downloaded,omitempty"`
	ConnectionToServer *Status_ConnectionToServer `protobuf:"varint,2,opt,name=connection_to_server,json=connectionToServer,enum=nanit.Status_ConnectionToServer" json:"connection_to_server,omitempty"`
	CurrentVersion     *string                    `protobuf:"bytes,3,opt,name=current_version,json=currentVersion" json:"current_version,omitempty"`
	Mode               *MountingMode              `protobuf:"varint,4,opt,name=mode,enum=nanit.MountingMode" json:"mode,omitempty"`
	IsSecurityUpgrade  *bool                      `protobuf:"varint,5,opt,name=is_security_upgrade,json=isSecurityUpgrade" json:"is_security_upgrade,omitempty"`
	DownloadedVersion  *string                    `protobuf:"bytes,6,opt,name=downloaded_version,json=downloadedVersion" json:"downloaded_version,omitempty"`
	HardwareVersion    *string                    `protobuf:"bytes,7,opt,name=hardware_version,json=hardwareVersion" json:"hardware_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_nanit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetUpgradeDownloaded() bool {
	if x != nil && x.UpgradeDownloaded != nil {
		return *x.UpgradeDownloaded
	}
	return false
}

func (x *Status) GetConnectionToServer() Status_ConnectionToServer {
	if x != nil && x.ConnectionToServer != nil {
		return *x.ConnectionToServer
	}
	return Status_DISCONNECTED
}

func (x *Status) GetCurrentVersion() string {
	if x != nil && x.CurrentVersion != nil {
		return *x.CurrentVersion
	}
	return ""
}

func (x *Status) GetMode() MountingMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return MountingMode_STAND
}

func (x *Status) GetIsSecurityUpgrade() bool {
	if x != nil && x.IsSecurityUpgrade != nil {
		return *x.IsSecurityUpgrade
	}
	return false
}

func (x *Status) GetDownloadedVersion() string {
	if x != nil && x.DownloadedVersion != nil {
		return *x.DownloadedVersion
	}
	return ""
}

func (x *Status) GetHardwareVersion() string {
	if x != nil && x.HardwareVersion != nil {
		return *x.HardwareVersion
	}
	return ""
}

type Playback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Playback_Status       `protobuf:"varint,1,req,name=status,enum=nanit.Playback_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playback) Reset() {
	*x = Playback{}
	mi := &file_proto_nanit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playback) ProtoMessage() {}

func (x *Playback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playback.ProtoReflect.Descriptor instead.
func (*Playback) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{6}
}

func (x *Playback) GetStatus() Playback_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Playback_STARTED
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Stream_Type           `protobuf:"varint,1,req,name=type,enum=nanit.Stream_Type" json:"type,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Bps           *int32                 `protobuf:"varint,3,opt,name=bps" json:"bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_proto_nanit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{7}
}

func (x *Stream) GetType() Stream_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Stream_LOCAL
}

func (x *Stream) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Stream) GetBps() int32 {
	if x != nil && x.Bps != nil {
		return *x.Bps
	}
	return 0
}

type Streaming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *StreamIdentifier      `protobuf:"varint,1,req,name=id,enum=nanit.StreamIdentifier" json:"id,omitempty"`
	Status        *Streaming_Status      `protobuf:"varint,2,req,name=status,enum=nanit.Streaming_Status" json:"status,omitempty"`
	RtmpUrl       *string                `protobuf:"bytes,3,req,name=rtmp_url,json=rtmpUrl" json:"rtmp_url,omitempty"`
	Attempts      *int32                 `protobuf:"varint,4,opt,name=attempts" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Streaming) Reset() {
	*x = Streaming{}
	mi := &file_proto_nanit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Streaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Streaming) ProtoMessage() {}

func (x *Streaming) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Streaming.ProtoReflect.Descriptor instead.
func (*Streaming) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{8}
}

func (x *Streaming) GetId() StreamIdentifier {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return StreamIdentifier_DVR
}

func (x *Streaming) GetStatus() Streaming_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Streaming_STARTED
}

func (x *Streaming) GetRtmpUrl() string {
	if x != nil && x.RtmpUrl != nil {
		return *x.RtmpUrl
	}
	return ""
}

func (x *Streaming) GetAttempts() int32 {
	if x != nil && x.Attempts != nil {
		return *x.Attempts
	}
	return 0
}

type GetLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogs) Reset() {
	*x = GetLogs{}
	mi := &file_proto_nanit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogs) ProtoMessage() {}

func (x *GetLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogs.ProtoReflect.Descriptor instead.
func (*GetLogs) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{9}
}

func (x *GetLogs) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type GetStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           *bool                  `protobuf:"varint,1,opt,name=all" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatus) Reset() {
	*x = GetStatus{}
	mi := &file_proto_nanit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatus) ProtoMessage() {}

func (x *GetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatus.ProtoReflect.Descriptor instead.
func (*GetStatus) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatus) GetAll() bool {
	if x != nil && x.All != nil {
		return *x.All
	}
	return false
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type          *RequestType           `protobuf:"varint,2,req,name=type,enum=nanit.RequestType" json:"type,omitempty"`
	Streaming     *Streaming             `protobuf:"bytes,4,opt,name=streaming" json:"streaming,omitempty"`
	Settings      *Settings              `protobuf:"bytes,5,opt,name=settings" json:"settings,omitempty"`
	Status        *Status                `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	GetStatus_    *GetStatus             `protobuf:"bytes,8,opt,name=get_status,json=getStatus" json:"get_status,omitempty"`
	GetSensorData *GetSensorData         `protobuf:"bytes,12,opt,name=get_sensor_data,json=getSensorData" json:"get_sensor_data,omitempty"`
	SensorData_   []*SensorData          `protobuf:"bytes,13,rep,name=sensor_data,json=sensorData" json:"sensor_data,omitempty"`
	Control       *Control               `protobuf:"bytes,15,opt,name=control" json:"control,omitempty"`
	Playback      *Playback              `protobuf:"bytes,16,opt,name=playback" json:"playback,omitempty"`
	GetControl_   *GetControl            `protobuf:"bytes,17,opt,name=get_control,json=getControl" json:"get_control,omitempty"`
	GetLogs       *GetLogs               `protobuf:"bytes,18,opt,name=get_logs,json=getLogs" json:"get_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_nanit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{11}
}

func (x *Request) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Request) GetType() RequestType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RequestType_PUT_STREAMING
}

func (x *Request) GetStreaming() *Streaming {
	if x != nil {
		return x.Streaming
	}
	return nil
}

func (x *Request) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Request) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Request) GetGetStatus_() *GetStatus {
	if x != nil {
		return x.GetStatus_
	}
	return nil
}

func (x *Request) GetGetSensorData() *GetSensorData {
	if x != nil {
		return x.GetSensorData
	}
	return nil
}

func (x *Request) GetSensorData_() []*SensorData {
	if x != nil {
		return x.SensorData_
	}
	return nil
}

func (x *Request) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Request) GetPlayback() *Playback {
	if x != nil {
		return x.Playback
	}
	return nil
}

func (x *Request) GetGetControl_() *GetControl {
	if x != nil {
		return x.GetControl_
	}
	return nil
}

func (x *Request) GetGetLogs() *GetLogs {
	if x != nil {
		return x.GetLogs
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *int32                 `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	RequestType   *RequestType           `protobuf:"varint,2,req,name=request_type,json=requestType,enum=nanit.RequestType" json:"request_type,omitempty"`
	StatusCode    *int32                 `protobuf:"varint,3,req,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMessage *string                `protobuf:"bytes,4,opt,name=status_message,json=statusMessage" json:"status_message,omitempty"`
	Status        *Status                `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	Settings      *Settings              `protobuf:"bytes,6,opt,name=settings" json:"settings,omitempty"`
	SensorData    []*SensorData          `protobuf:"bytes,9,rep,name=sensor_data,json=sensorData" json:"sensor_data,omitempty"`
	Control       *Control               `protobuf:"bytes,13,opt,name=control" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_nanit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetRequestId() int32 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *Response) GetRequestType() RequestType {
	if x != nil && x.RequestType != nil {
		return *x.RequestType
	}
	return RequestType_PUT_STREAMING
}

func (x *Response) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *Response) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

func (x *Response) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Response) GetSensorData() []*SensorData {
	if x != nil {
		return x.SensorData
	}
	return nil
}

func (x *Response) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Message_Type          `protobuf:"varint,1,req,name=type,enum=nanit.Message_Type" json:"type,omitempty"`
	Request       *Request               `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response      *Response              `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_nanit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{13}
}

func (x *Message) GetType() Message_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Message_KEEPALIVE
}

func (x *Message) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Message) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Control_SensorDataTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sound         *bool                  `protobuf:"varint,1,opt,name=sound" json:"sound,omitempty"`
	Motion        *bool                  `protobuf:"varint,2,opt,name=motion" json:"motion,omitempty"`
	Temperature   *bool                  `protobuf:"varint,3,opt,name=temperature" json:"temperature,omitempty"`
	Humidity      *bool                  `protobuf:"varint,4,opt,name=humidity" json:"humidity,omitempty"`
	Light         *bool                  `protobuf:"varint,5,opt,name=light" json:"light,omitempty"`
	Night         *bool                  `protobuf:"varint,6,opt,name=night" json:"night,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control_SensorDataTransfer) Reset() {
	*x = Control_SensorDataTransfer{}
	mi := &file_proto_nanit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control_SensorDataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control_SensorDataTransfer) ProtoMessage() {}

func (x *Control_SensorDataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control_SensorDataTransfer.ProtoReflect.Descriptor instead.
func (*Control_SensorDataTransfer) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Control_SensorDataTransfer) GetSound() bool {
	if x != nil && x.Sound != nil {
		return *x.Sound
	}
	return false
}

func (x *Control_SensorDataTransfer) GetMotion() bool {
	if x != nil && x.Motion != nil {
		return *x.Motion
	}
	return false
}

func (x *Control_SensorDataTransfer) GetTemperature() bool {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return false
}

func (x *Control_SensorDataTransfer) GetHumidity() bool {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return false
}

func (x *Control_SensorDataTransfer) GetLight() bool {
	if x != nil && x.Light != nil {
		return *x.Light
	}
	return false
}

func (x *Control_SensorDataTransfer) GetNight() bool {
	if x != nil && x.Night != nil {
		return *x.Night
	}
	return false
}

type Settings_SensorSettings struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SensorType            *SensorType            `protobuf:"varint,1,req,name=sensor_type,json=sensorType,enum=nanit.SensorType" json:"sensor_type,omitempty"`
	UseLowThreshold       *bool                  `protobuf:"varint,2,opt,name=use_low_threshold,json=useLowThreshold" json:"use_low_threshold,omitempty"`
	UseHighThreshold      *bool                  `protobuf:"varint,3,opt,name=use_high_threshold,json=useHighThreshold" json:"use_high_threshold,omitempty"`
	LowThreshold          *int32                 `protobuf:"varint,4,opt,name=low_threshold,json=lowThreshold" json:"low_threshold,omitempty"`
	HighThreshold         *int32                 `protobuf:"varint,5,opt,name=high_threshold,json=highThreshold" json:"high_threshold,omitempty"`
	SampleIntervalSec     *int32                 `protobuf:"varint,6,opt,name=sample_interval_sec,json=sampleIntervalSec" json:"sample_interval_sec,omitempty"`
	TriggerIntervalSec    *int32                 `protobuf:"varint,7,opt,name=trigger_interval_sec,json=triggerIntervalSec" json:"trigger_interval_sec,omitempty"`
	UseMilliForThresholds *bool                  `protobuf:"varint,8,opt,name=use_milli_for_thresholds,json=useMilliForThresholds" json:"use_milli_for_thresholds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Settings_SensorSettings) Reset() {
	*x = Settings_SensorSettings{}
	mi := &file_proto_nanit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings_SensorSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings_SensorSettings) ProtoMessage() {}

func (x *Settings_SensorSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings_SensorSettings.ProtoReflect.Descriptor instead.
func (*Settings_SensorSettings) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Settings_SensorSettings) GetSensorType() SensorType {
	if x != nil && x.SensorType != nil {
		return *x.SensorType
	}
	return SensorType_SOUND
}

func (x *Settings_SensorSettings) GetUseLowThreshold() bool {
	if x != nil && x.UseLowThreshold != nil {
		return *x.UseLowThreshold
	}
	return false
}

func (x *Settings_SensorSettings) GetUseHighThreshold() bool {
	if x != nil && x.UseHighThreshold != nil {
		return *x.UseHighThreshold
	}
	return false
}

func (x *Settings_SensorSettings) GetLowThreshold() int32 {
	if x != nil && x.LowThreshold != nil {
		return *x.LowThreshold
	}
	return 0
}

func (x *Settings_SensorSettings) GetHighThreshold() int32 {
	if x != nil && x.HighThreshold != nil {
		return *x.HighThreshold
	}
	return 0
}

func (x *Settings_SensorSettings) GetSampleIntervalSec() int32 {
	if x != nil && x.SampleIntervalSec != nil {
		return *x.SampleIntervalSec
	}
	return 0
}

func (x *Settings_SensorSettings) GetTriggerIntervalSec() int32 {
	if x != nil && x.TriggerIntervalSec != nil {
		return *x.TriggerIntervalSec
	}
	return 0
}

func (x *Settings_SensorSettings) GetUseMilliForThresholds() bool {
	if x != nil && x.UseMilliForThresholds != nil {
		return *x.UseMilliForThresholds
	}
	return false
}

type Settings_StreamSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *StreamIdentifier      `protobuf:"varint,1,req,name=id,enum=nanit.StreamIdentifier" json:"id,omitempty"`
	Bitrate        *int32                 `protobuf:"varint,2,opt,name=bitrate" json:"bitrate,omitempty"`
	EconomyBitrate *int32                 `protobuf:"varint,3,opt,name=economy_bitrate,json=economyBitrate" json:"economy_bitrate,omitempty"`
	EconomyFps     *int32                 `protobuf:"varint,4,opt,name=economy_fps,json=economyFps" json:"economy_fps,omitempty"`
	BestBitrate    *int32                 `protobuf:"varint,5,opt,name=best_bitrate,json=bestBitrate" json:"best_bitrate,omitempty"`
	BestFps        *int32                 `protobuf:"varint,6,opt,name=best_fps,json=bestFps" json:"best_fps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Settings_StreamSettings) Reset() {
	*x = Settings_StreamSettings{}
	mi := &file_proto_nanit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings_StreamSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings_StreamSettings) ProtoMessage() {}

func (x *Settings_StreamSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nanit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings_StreamSettings.ProtoReflect.Descriptor instead.
func (*Settings_StreamSettings) Descriptor() ([]byte, []int) {
	return file_proto_nanit_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Settings_StreamSettings) GetId() StreamIdentifier {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return StreamIdentifier_DVR
}

func (x *Settings_StreamSettings) GetBitrate() int32 {
	if x != nil && x.Bitrate != nil {
		return *x.Bitrate
	}
	return 0
}

func (x *Settings_StreamSettings) GetEconomyBitrate() int32 {
	if x != nil && x.EconomyBitrate != nil {
		return *x.EconomyBitrate
	}
	return 0
}

func (x *Settings_StreamSettings) GetEconomyFps() int32 {
	if x != nil && x.EconomyFps != nil {
		return *x.EconomyFps
	}
	return 0
}

func (x *Settings_StreamSettings) GetBestBitrate() int32 {
	if x != nil && x.BestBitrate != nil {
		return *x.BestBitrate
	}
	return 0
}

func (x *Settings_StreamSettings) GetBestFps() int32 {
	if x != nil && x.BestFps != nil {
		return *x.BestFps
	}
	return 0
}

var File_proto_nanit_proto protoreflect.FileDescriptor

const file_proto_nanit_proto_rawDesc = "" +
	"\n" +
	"\x11proto/nanit.proto\x12\x05nanit\"\xb0\x01\n" +
	"\n" +
	"SensorData\x122\n" +
	"\vsensor_type\x18\x01 \x02(\x0e2\x11.nanit.SensorTypeR\n" +
	"sensorType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x19\n" +
	"\bis_alert\x18\x04 \x01(\bR\aisAlert\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x05R\ttimestamp\x12\x1f\n" +
	"\vvalue_milli\x18\x06 \x01(\x05R\n" +
	"valueMilli\"\x8b\x01\n" +
	"\rGetSensorData\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12 \n" +
	"\vtemperature\x18\x04 \x01(\bR\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\bR\bhumidity\x12\x14\n" +
	"\x05light\x18\x06 \x01(\bR\x05light\x12\x14\n" +
	"\x05night\x18\a \x01(\bR\x05night\"\xa6\x01\n" +
	"\n" +
	"GetControl\x12\x10\n" +
	"\x03ptz\x18\x01 \x01(\bR\x03ptz\x12\x1f\n" +
	"\vnight_light\x18\x02 \x01(\bR\n" +
	"nightLight\x12.\n" +
	"\x13night_light_timeout\x18\x03 \x01(\bR\x11nightLightTimeout\x125\n" +
	"\x17sensor_data_transfer_en\x18\x04 \x01(\bR\x14sensorDataTransferEn\"\xdb\x03\n" +
	"\aControl\x12:\n" +
	"\vnight_light\x18\x03 \x01(\x0e2\x19.nanit.Control.NightLightR\n" +
	"nightLight\x12S\n" +
	"\x14sensor_data_transfer\x18\x04 \x01(\v2!.nanit.Control.SensorDataTransferR\x12sensorDataTransfer\x125\n" +
	"\x17force_connect_to_server\x18\x05 \x01(\bR\x14forceConnectToServer\x12.\n" +
	"\x13night_light_timeout\x18\x06 \x01(\x05R\x11nightLightTimeout\x1a\xac\x01\n" +
	"\x12SensorDataTransfer\x12\x14\n" +
	"\x05sound\x18\x01 \x01(\bR\x05sound\x12\x16\n" +
	"\x06motion\x18\x02 \x01(\bR\x06motion\x12 \n" +
	"\vtemperature\x18\x03 \x01(\bR\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\bR\bhumidity\x12\x14\n" +
	"\x05light\x18\x05 \x01(\bR\x05light\x12\x14\n" +
	"\x05night\x18\x06 \x01(\bR\x05night\")\n" +
	"\n" +
	"NightLight\x12\r\n" +
	"\tLIGHT_OFF\x10\x00\x12\f\n" +
	"\bLIGHT_ON\x10\x01\"\xfa\b\n" +
	"\bSettings\x12!\n" +
	"\fnight_vision\x18\x02 \x01(\bR\vnightVision\x128\n" +
	"\asensors\x18\a \x03(\v2\x1e.nanit.Settings.SensorSettingsR\asensors\x128\n" +
	"\astreams\x18\b \x03(\v2\x1e.nanit.Settings.StreamSettingsR\astreams\x12\x16\n" +
	"\x06volume\x18\t \x01(\x05R\x06volume\x12>\n" +
	"\fanti_flicker\x18\n" +
	" \x01(\x0e2\x1b.nanit.Settings.AntiFlickerR\vantiFlicker\x12\x1d\n" +
	"\n" +
	"sleep_mode\x18\v \x01(\bR\tsleepMode\x12&\n" +
	"\x0fstatus_light_on\x18\f \x01(\bR\rstatusLightOn\x12#\n" +
	"\rmounting_mode\x18\x0f \x01(\x05R\fmountingMode\x125\n" +
	"\twifi_band\x18\x12 \x01(\x0e2\x18.nanit.Settings.WifiBandR\bwifiBand\x12\x1e\n" +
	"\vmic_mute_on\x18\x14 \x01(\bR\tmicMuteOn\x1a\x85\x03\n" +
	"\x0eSensorSettings\x122\n" +
	"\vsensor_type\x18\x01 \x02(\x0e2\x11.nanit.SensorTypeR\n" +
	"sensorType\x12*\n" +
	"\x11use_low_threshold\x18\x02 \x01(\bR\x0fuseLowThreshold\x12,\n" +
	"\x12use_high_threshold\x18\x03 \x01(\bR\x10useHighThreshold\x12#\n" +
	"\rlow_threshold\x18\x04 \x01(\x05R\flowThreshold\x12%\n" +
	"\x0ehigh_threshold\x18\x05 \x01(\x05R\rhighThreshold\x12.\n" +
	"\x13sample_interval_sec\x18\x06 \x01(\x05R\x11sampleIntervalSec\x120\n" +
	"\x14trigger_interval_sec\x18\a \x01(\x05R\x12triggerIntervalSec\x127\n" +
	"\x18use_milli_for_thresholds\x18\b \x01(\bR\x15useMilliForThresholds\x1a\xdb\x01\n" +
	"\x0eStreamSettings\x12'\n" +
	"\x02id\x18\x01 \x02(\x0e2\x17.nanit.StreamIdentifierR\x02id\x12\x18\n" +
	"\abitrate\x18\x02 \x01(\x05R\abitrate\x12'\n" +
	"\x0feconomy_bitrate\x18\x03 \x01(\x05R\x0eeconomyBitrate\x12\x1f\n" +
	"\veconomy_fps\x18\x04 \x01(\x05R\n" +
	"economyFps\x12!\n" +
	"\fbest_bitrate\x18\x05 \x01(\x05R\vbestBitrate\x12\x19\n" +
	"\bbest_fps\x18\x06 \x01(\x05R\abestFps\"%\n" +
	"\vAntiFlicker\x12\n" +
	"\n" +
	"\x06FR50HZ\x10\x00\x12\n" +
	"\n" +
	"\x06FR60HZ\x10\x01\"/\n" +
	"\bWifiBand\x12\a\n" +
	"\x03ANY\x10\x00\x12\f\n" +
	"\bFR2_4GHZ\x10\x01\x12\f\n" +
	"\bFR5_0GHZ\x10\x02\"\x9e\x03\n" +
	"\x06Status\x12-\n" +
	"\x12upgrade_downloaded\x18\x01 \x01(\bR\x11upgradeDownloaded\x12R\n" +
	"\x14connection_to_server\x18\x02 \x01(\x0e2 .nanit.Status.ConnectionToServerR\x12connectionToServer\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\tR\x0ecurrentVersion\x12'\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x13.nanit.MountingModeR\x04mode\x12.\n" +
	"\x13is_security_upgrade\x18\x05 \x01(\bR\x11isSecurityUpgrade\x12-\n" +
	"\x12downloaded_version\x18\x06 \x01(\tR\x11downloadedVersion\x12)\n" +
	"\x10hardware_version\x18\a \x01(\tR\x0fhardwareVersion\"5\n" +
	"\x12ConnectionToServer\x12\x10\n" +
	"\fDISCONNECTED\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\"^\n" +
	"\bPlayback\x12.\n" +
	"\x06status\x18\x01 \x02(\x0e2\x16.nanit.Playback.StatusR\x06status\"\"\n" +
	"\x06Status\x12\v\n" +
	"\aSTARTED\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\"\x86\x01\n" +
	"\x06Stream\x12&\n" +
	"\x04type\x18\x01 \x02(\x0e2\x12.nanit.Stream.TypeR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x10\n" +
	"\x03bps\x18\x03 \x01(\x05R\x03bps\"0\n" +
	"\x04Type\x12\t\n" +
	"\x05LOCAL\x10\x00\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x01\x12\b\n" +
	"\x04RTSP\x10\x02\x12\a\n" +
	"\x03P2P\x10\x03\"\xcc\x01\n" +
	"\tStreaming\x12'\n" +
	"\x02id\x18\x01 \x02(\x0e2\x17.nanit.StreamIdentifierR\x02id\x12/\n" +
	"\x06status\x18\x02 \x02(\x0e2\x17.nanit.Streaming.StatusR\x06status\x12\x19\n" +
	"\brtmp_url\x18\x03 \x02(\tR\artmpUrl\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\".\n" +
	"\x06Status\x12\v\n" +
	"\aSTARTED\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02\"\x1b\n" +
	"\aGetLogs\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\"\x1d\n" +
	"\tGetStatus\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"\x9e\x04\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\x05R\x02id\x12&\n" +
	"\x04type\x18\x02 \x02(\x0e2\x12.nanit.RequestTypeR\x04type\x12.\n" +
	"\tstreaming\x18\x04 \x01(\v2\x10.nanit.StreamingR\tstreaming\x12+\n" +
	"\bsettings\x18\x05 \x01(\v2\x0f.nanit.SettingsR\bsettings\x12%\n" +
	"\x06status\x18\a \x01(\v2\r.nanit.StatusR\x06status\x12/\n" +
	"\n" +
	"get_status\x18\b \x01(\v2\x10.nanit.GetStatusR\tgetStatus\x12<\n" +
	"\x0fget_sensor_data\x18\f \x01(\v2\x14.nanit.GetSensorDataR\rgetSensorData\x122\n" +
	"\vsensor_data\x18\r \x03(\v2\x11.nanit.SensorDataR\n" +
	"sensorData\x12(\n" +
	"\acontrol\x18\x0f \x01(\v2\x0e.nanit.ControlR\acontrol\x12+\n" +
	"\bplayback\x18\x10 \x01(\v2\x0f.nanit.PlaybackR\bplayback\x122\n" +
	"\vget_control\x18\x11 \x01(\v2\x11.nanit.GetControlR\n" +
	"getControl\x12)\n" +
	"\bget_logs\x18\x12 \x01(\v2\x0e.nanit.GetLogsR\agetLogs\"\xda\x02\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x02(\x05R\trequestId\x125\n" +
	"\frequest_type\x18\x02 \x02(\x0e2\x12.nanit.RequestTypeR\vrequestType\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x02(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\x12%\n" +
	"\x06status\x18\x05 \x01(\v2\r.nanit.StatusR\x06status\x12+\n" +
	"\bsettings\x18\x06 \x01(\v2\x0f.nanit.SettingsR\bsettings\x122\n" +
	"\vsensor_data\x18\t \x03(\v2\x11.nanit.SensorDataR\n" +
	"sensorData\x12(\n" +
	"\acontrol\x18\r \x01(\v2\x0e.nanit.ControlR\acontrol\"\xbb\x01\n" +
	"\aMessage\x12'\n" +
	"\x04type\x18\x01 \x02(\x0e2\x13.nanit.Message.TypeR\x04type\x12(\n" +
	"\arequest\x18\x02 \x01(\v2\x0e.nanit.RequestR\arequest\x12+\n" +
	"\bresponse\x18\x03 \x01(\v2\x0f.nanit.ResponseR\bresponse\"0\n" +
	"\x04Type\x12\r\n" +
	"\tKEEPALIVE\x10\x00\x12\v\n" +
	"\aREQUEST\x10\x01\x12\f\n" +
	"\bRESPONSE\x10\x02*\xe0\x06\n" +
	"\vRequestType\x12\x11\n" +
	"\rPUT_STREAMING\x10\x02\x12\x11\n" +
	"\rGET_STREAMING\x10\x03\x12\x10\n" +
	"\fGET_SETTINGS\x10\x04\x12\x10\n" +
	"\fPUT_SETTINGS\x10\x05\x12\x0f\n" +
	"\vGET_CONTROL\x10\x06\x12\x0f\n" +
	"\vPUT_CONTROL\x10\a\x12\x0e\n" +
	"\n" +
	"GET_STATUS\x10\b\x12\x0e\n" +
	"\n" +
	"PUT_STATUS\x10\t\x12\x13\n" +
	"\x0fPUT_SENSOR_DATA\x10\v\x12\x13\n" +
	"\x0fGET_SENSOR_DATA\x10\f\x12\x10\n" +
	"\fGET_UCTOKENS\x10\r\x12\x10\n" +
	"\fPUT_UCTOKENS\x10\x0e\x12\x15\n" +
	"\x11PUT_SETUP_NETWORK\x10\x0f\x12\x14\n" +
	"\x10PUT_SETUP_SERVER\x10\x10\x12\x10\n" +
	"\fGET_FIRMWARE\x10\x11\x12\x10\n" +
	"\fPUT_FIRMWARE\x10\x12\x12\x10\n" +
	"\fGET_PLAYBACK\x10\x13\x12\x10\n" +
	"\fPUT_PLAYBACK\x10\x14\x12\x13\n" +
	"\x0fGET_SOUNDTRACKS\x10\x15\x12\x16\n" +
	"\x12GET_STATUS_NETWORK\x10\x16\x12\x15\n" +
	"\x11GET_LIST_NETWORKS\x10\x17\x12\f\n" +
	"\bGET_LOGS\x10\x18\x12\x11\n" +
	"\rGET_BANDWIDTH\x10\x19\x12\x17\n" +
	"\x13GET_AUDIO_STREAMING\x10\x1a\x12\x17\n" +
	"\x13PUT_AUDIO_STREAMING\x10\x1b\x12\x12\n" +
	"\x0eGET_WIFI_SETUP\x10\x1c\x12\x12\n" +
	"\x0ePUT_WIFI_SETUP\x10\x1d\x12\x13\n" +
	"\x0fPUT_STING_START\x10\x1e\x12\x12\n" +
	"\x0ePUT_STING_STOP\x10\x1f\x12\x14\n" +
	"\x10PUT_STING_STATUS\x10 \x12\x13\n" +
	"\x0fPUT_STING_ALERT\x10\"\x12\x12\n" +
	"\x0ePUT_KEEP_ALIVE\x10#\x12\x14\n" +
	"\x10GET_STING_STATUS\x10$\x12\x12\n" +
	"\x0ePUT_STING_TEST\x10%\x12\x16\n" +
	"\x12PUT_RTSP_STREAMING\x10&\x12\x0f\n" +
	"\vGET_UOM_URI\x10'\x12\v\n" +
	"\aGET_UOM\x10(\x12\v\n" +
	"\aPUT_UOM\x10)\x12\x10\n" +
	"\fGET_AUTH_KEY\x10*\x12\x10\n" +
	"\fPUT_AUTH_KEY\x10+\x12\x0e\n" +
	"\n" +
	"PUT_HEALTH\x10,\x12\x13\n" +
	"\x0fPUT_TCP_REQUEST\x10-\x12\x13\n" +
	"\x0fGET_STING_START\x10.\x12\x10\n" +
	"\fGET_LOGS_URI\x10/*X\n" +
	"\n" +
	"SensorType\x12\t\n" +
	"\x05SOUND\x10\x00\x12\n" +
	"\n" +
	"\x06MOTION\x10\x01\x12\x0f\n" +
	"\vTEMPERATURE\x10\x02\x12\f\n" +
	"\bHUMIDITY\x10\x03\x12\t\n" +
	"\x05LIGHT\x10\x04\x12\t\n" +
	"\x05NIGHT\x10\x05*6\n" +
	"\x10StreamIdentifier\x12\a\n" +
	"\x03DVR\x10\x00\x12\r\n" +
	"\tANALYTICS\x10\x01\x12\n" +
	"\n" +
	"\x06MOBILE\x10\x02*1\n" +
	"\fMountingMode\x12\t\n" +
	"\x05STAND\x10\x00\x12\n" +
	"\n" +
	"\x06TRAVEL\x10\x01\x12\n" +
	"\n" +
	"\x06SWITCH\x10\x02B8Z6github.com/trymwestin/nanit/internal/core/transport/pb"

var (
	file_proto_nanit_proto_rawDescOnce sync.Once
	file_proto_nanit_proto_rawDescData []byte
)

func file_proto_nanit_proto_rawDescGZIP() []byte {
	file_proto_nanit_proto_rawDescOnce.Do(func() {
		file_proto_nanit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nanit_proto_rawDesc), len(file_proto_nanit_proto_rawDesc)))
	})
	return file_proto_nanit_proto_rawDescData
}

var file_proto_nanit_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_proto_nanit_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_nanit_proto_goTypes = []any{
	(RequestType)(0),                   // 0: nanit.RequestType
	(SensorType)(0),                    // 1: nanit.SensorType
	(StreamIdentifier)(0),              // 2: nanit.StreamIdentifier
	(MountingMode)(0),                  // 3: nanit.MountingMode
	(Control_NightLight)(0),            // 4: nanit.Control.NightLight
	(Settings_AntiFlicker)(0),          // 5: nanit.Settings.AntiFlicker
	(Settings_WifiBand)(0),             // 6: nanit.Settings.WifiBand
	(Status_ConnectionToServer)(0),     // 7: nanit.Status.ConnectionToServer
	(Playback_Status)(0),               // 8: nanit.Playback.Status
	(Stream_Type)(0),                   // 9: nanit.Stream.Type
	(Streaming_Status)(0),              // 10: nanit.Streaming.Status
	(Message_Type)(0),                  // 11: nanit.Message.Type
	(*SensorData)(nil),                 // 12: nanit.SensorData
	(*GetSensorData)(nil),              // 13: nanit.GetSensorData
	(*GetControl)(nil),                 // 14: nanit.GetControl
	(*Control)(nil),                    // 15: nanit.Control
	(*Settings)(nil),                   // 16: nanit.Settings
	(*Status)(nil),                     // 17: nanit.Status
	(*Playback)(nil),                   // 18: nanit.Playback
	(*Stream)(nil),                     // 19: nanit.Stream
	(*Streaming)(nil),                  // 20: nanit.Streaming
	(*GetLogs)(nil),                    // 21: nanit.GetLogs
	(*GetStatus)(nil),                  // 22: nanit.GetStatus
	(*Request)(nil),                    // 23: nanit.Request
	(*Response)(nil),                   // 24: nanit.Response
	(*Message)(nil),                    // 25: nanit.Message
	(*Control_SensorDataTransfer)(nil), // 26: nanit.Control.SensorDataTransfer
	(*Settings_SensorSettings)(nil),    // 27: nanit.Settings.SensorSettings
	(*Settings_StreamSettings)(nil),    // 28: nanit.Settings.StreamSettings
}
var file_proto_nanit_proto_depIdxs = []int32{
	1,  // 0: nanit.SensorData.sensor_type:type_name -> nanit.SensorType
	4,  // 1: nanit.Control.night_light:type_name -> nanit.Control.NightLight
	26, // 2: nanit.Control.sensor_data_transfer:type_name -> nanit.Control.SensorDataTransfer
	27, // 3: nanit.Settings.sensors:type_name -> nanit.Settings.SensorSettings
	28, // 4: nanit.Settings.streams:type_name -> nanit.Settings.StreamSettings
	5,  // 5: nanit.Settings.anti_flicker:type_name -> nanit.Settings.AntiFlicker
	6,  // 6: nanit.Settings.wifi_band:type_name -> nanit.Settings.WifiBand
	7,  // 7: nanit.Status.connection_to_server:type_name -> nanit.Status.ConnectionToServer
	3,  // 8: nanit.Status.mode:type_name -> nanit.MountingMode
	8,  // 9: nanit.Playback.status:type_name -> nanit.Playback.Status
	9,  // 10: nanit.Stream.type:type_name -> nanit.Stream.Type
	2,  // 11: nanit.Streaming.id:type_name -> nanit.StreamIdentifier
	10, // 12: nanit.Streaming.status:type_name -> nanit.Streaming.Status
	0,  // 13: nanit.Request.type:type_name -> nanit.RequestType
	20, // 14: nanit.Request.streaming:type_name -> nanit.Streaming
	16, // 15: nanit.Request.settings:type_name -> nanit.Settings
	17, // 16: nanit.Request.status:type_name -> nanit.Status
	22, // 17: nanit.Request.get_status:type_name -> nanit.GetStatus
	13, // 18: nanit.Request.get_sensor_data:type_name -> nanit.GetSensorData
	12, // 19: nanit.Request.sensor_data:type_name -> nanit.SensorData
	15, // 20: nanit.Request.control:type_name -> nanit.Control
	18, // 21: nanit.Request.playback:type_name -> nanit.Playback
	14, // 22: nanit.Request.get_control:type_name -> nanit.GetControl
	21, // 23: nanit.Request.get_logs:type_name -> nanit.GetLogs
	0,  // 24: nanit.Response.request_type:type_name -> nanit.RequestType
	17, // 25: nanit.Response.status:type_name -> nanit.Status
	16, // 26: nanit.Response.settings:type_name -> nanit.Settings
	12, // 27: nanit.Response.sensor_data:type_name -> nanit.SensorData
	15, // 28: nanit.Response.control:type_name -> nanit.Control
	11, // 29: nanit.Message.type:type_name -> nanit.Message.Type
	23, // 30: nanit.Message.request:type_name -> nanit.Request
	24, // 31: nanit.Message.response:type_name -> nanit.Response
	1,  // 32: nanit.Settings.SensorSettings.sensor_type:type_name -> nanit.SensorType
	2,  // 33: nanit.Settings.StreamSettings.id:type_name -> nanit.StreamIdentifier
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_proto_nanit_proto_init() }
func file_proto_nanit_proto_init() {
	if File_proto_nanit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nanit_proto_rawDesc), len(file_proto_nanit_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_nanit_proto_goTypes,
		DependencyIndexes: file_proto_nanit_proto_depIdxs,
		EnumInfos:         file_proto_nanit_proto_enumTypes,
		MessageInfos:      file_proto_nanit_proto_msgTypes,
	}.Build()
	File_proto_nanit_proto = out.File
	file_proto_nanit_proto_goTypes = nil
	file_proto_nanit_proto_depIdxs = nil
}
